name: ShadowList
version: 1.0
main: net.teamshadowmc.shadowlist.ShadowList
author: ["Fayettemat", "-_Husky_-"]
description: MySQL Whitelisting plugin
commands:
  sqlist:
    description:
    usage:
  wl:
   description:
   usage:
  shadowlist:
    description:
    usage: