name: ${project.name}
version: ${project.version}
main: net.teamshadowmc.shadowlist.ShadowList
author: ["Fayettemat", "-_Husky_-"]
description: ${project.description}
commands:
  wl:
   description: Whitelist replacement command
   usage: See /wl help for usage.
