name: ShadowList
version: 1.0-SNAPSHOT
main: net.teamshadowmc.shadowlist.ShadowList
author: ["Fayettemat", "-_Husky_-"]
description: MySQL Whitelisting plugin
commands:
  wl:
   description: Whitelist replacement command
   usage: See /wl help for usage.
